### PR TITLE
Feature [Allow Optionals Params]

### PR DESCRIPTION
**Pull request by Baxi19**
## Pull Request Summary

This pull request introduces several enhancements and updates to the codebase. The changes include the addition of new functionality, internal documentation updates, improvements to the `README.md` file, the creation of a new class, updates to the `concatUserFlow` method, and UI refinements using the `Visibility` widget.

## Changes Made

1. Added the ability to include optional parameters in the `AADLoginButton` widget to customize the URL. The `optionalParameters` parameter now accepts a list of `OptionalParam` objects, where each object represents a parameter name and its corresponding value.

2. Updated the `README.md` file to include detailed instructions on how to utilize the `optionalParameters` parameter. An example was provided to demonstrate the addition of new parameters to the URL.

3. Created a new class, `OptionalParam`, to encapsulate the key-value pairs for the optional parameters.

4. Improved the `concatUserFlow` method to incorporate the optional parameters in the URL generation process.

5. Updated the UI implementation to utilize the `Visibility` widget. This change allows for the removal of unnecessary `Stack` widgets, resulting in a cleaner and more efficient UI structure.

These changes enhance the flexibility and customization options of the `AADLoginButton` widget, while also improving code organization, readability, and user experience.

Please review the changes and provide any feedback or suggestions for further improvements.

Thank you.

### CODE REVIEW

**Comment by Baxi19** [comment]
@microsoft-github-policy-service agree company="nnoxx-inc"

**Comment by Baxi19** [comment]
Marking this pull request as ready for review.

**Comment by mohanajuhi166** [comment]
@Baxi19  thank you for your contribution, I will review it in some days :)

**Review by mohanajuhi166 — APPROVED** [review]
LGTM :)

**Comment by Baxi19** [comment]
Hi @mohanajuhi166

What is the next step to merge this pull request?

**Comment by mohanajuhi166** [comment]
@Baxi19 thank you for your contribution, it's deployed now to pub.dev

We would love to know how this package is being currently utilized as we want to add a documentation going forward and also open up issues/features :)

Kind regards,
Mohana

**Comment by Baxi19** [comment]
Hello @mohanajuhi166 ,

Thank you for reviewing my pull request. 

Currently, the package is being used in a project where it serves as a WebView for Azure Active Directory B2C authentication.

In this particular project, we required the ability to include an optional parameter in the URL to differentiate between `app mobile` and `web page` sources. This addition allows us to handle different scenarios and customize the behavior accordingly.

By adding support for optional parameters, it enhances the flexibility and adaptability of the package, making it more versatile for various use cases.

If you have any further questions or need additional information, please feel free to let me know. I'm glad to assist you in any way I can.

Best regards,
Randald Villegas.

**Comment by mohanajuhi166** [comment]
thanks @Baxi19 !, if you want to be one of the active contributors here ,let us know :) .

**Comment by Baxi19** [comment]
@mohanajuhi166  Yes, I would like to be one of the active contributors here. 
I am eager to contribute and assist in any way I can.

**Comment by mohanajuhi166** [comment]
@Baxi19 thank you!! will include you as a reviewer for other pull requests etc :)

**Pull request merged**
